version: '2'

volumes:
  db_data:
    driver: local

services:
  app:
    image: 'yumeinaruu/links:v1'
    build:
      context: .
    container_name: links
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - tracker_network

  db:
    image: 'postgres:16.1'
    container_name: links_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tracker_network

networks:
  tracker_network:
    driver: bridge
